# Generated by Django 4.2.7 on 2024-01-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Uploaded Image')),
                ('result', models.TextField(blank=True, verbose_name='Kimi Analysis Result')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Time')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processing Time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Processed Image',
                'verbose_name_plural': 'Processed Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]