# Generated by Django 4.2.29 on 2026-03-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGImageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_count', models.IntegerField(default=0, verbose_name='槽特征数量')),
                ('hole_count', models.IntegerField(default=0, verbose_name='孔特征数量')),
                ('chamfer_count', models.IntegerField(default=0, verbose_name='倒角特征数量')),
                ('shoulder_count', models.IntegerField(default=0, verbose_name='肩特征数量')),
                ('step_count', models.IntegerField(default=0, verbose_name='阶特征数量')),
                ('slot_positions', models.TextField(blank=True, verbose_name='槽特征位置描述')),
                ('hole_positions', models.TextField(blank=True, verbose_name='孔特征位置描述')),
                ('chamfer_positions', models.TextField(blank=True, verbose_name='倒角特征位置描述')),
                ('shoulder_positions', models.TextField(blank=True, verbose_name='肩特征位置描述')),
                ('step_positions', models.TextField(blank=True, verbose_name='阶特征位置描述')),
                ('feature_vector', models.JSONField(blank=True, default=dict, verbose_name='特征向量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('processed_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rag_features', to='imageprocessor.processedimage')),
            ],
            options={
                'verbose_name': 'RAG图片特征',
                'verbose_name_plural': 'RAG图片特征',
                'ordering': ['-created_at'],
            },
        ),
    ]
