# Generated by Django 4.2.29 on 2026-03-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0002_ragimagefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragimagefeature',
            name='approval_status',
            field=models.CharField(choices=[('pending_review', '待审核'), ('approved', '已审核'), ('rejected', '已拒绝')], default='pending_review', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='ragimagefeature',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='ragimagefeature',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='ragimagefeature',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='审核者'),
        ),
    ]
