# Generated by Django 4.2.29 on 2026-03-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0003_ragimagefeature_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='upload_type',
            field=models.CharField(choices=[('user', '用户上传'), ('admin_rag', '管理员RAG上传')], default='user', max_length=20, verbose_name='上传类型'),
        ),
    ]
