# Generated by Django 4.2.29 on 2026-04-08 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0004_processedimage_upload_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(help_text='如：F1, F2, F3...', max_length=20, verbose_name='特征名称')),
                ('operation', models.CharField(choices=[('milling', '铣削'), ('drilling', '钻孔'), ('centre drilling', '中心钻')], max_length=50, verbose_name='工序')),
                ('prior_operations', models.CharField(blank=True, help_text='如：none, centre drilling, milling等', max_length=200, verbose_name='前置工序')),
                ('machine', models.CharField(blank=True, help_text='选中的机器，如：m1, m2, m3, m4, m5', max_length=50, verbose_name='机器')),
                ('tool', models.CharField(blank=True, help_text='选中的刀具，多个用逗号分隔，如：t1,t2,t3', max_length=200, verbose_name='刀具')),
                ('is_chamfer_second', models.BooleanField(default=False, help_text='如果是倒角的第二个milling工序，Tool固定为t11', verbose_name='是否为倒角第二工序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('processed_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_selections', to='imageprocessor.processedimage', verbose_name='处理的图片')),
            ],
            options={
                'verbose_name': '工艺选择',
                'verbose_name_plural': '工艺选择',
                'ordering': ['feature_name', 'operation'],
                'unique_together': {('processed_image', 'feature_name', 'operation')},
            },
        ),
    ]
