# Generated by Django 4.2.29 on 2026-04-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0005_processselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processselection',
            options={'ordering': ['feature_name', 'sequence', 'operation'], 'verbose_name': '工艺选择', 'verbose_name_plural': '工艺选择'},
        ),
        migrations.AlterUniqueTogether(
            name='processselection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='processselection',
            name='sequence',
            field=models.IntegerField(default=0, help_text='同一特征的不同行的序号，从0开始', verbose_name='序号'),
        ),
        migrations.AlterUniqueTogether(
            name='processselection',
            unique_together={('processed_image', 'feature_name', 'sequence', 'operation')},
        ),
    ]
