# Generated by Django 4.2.29 on 2026-04-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0006_alter_processselection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragimagefeature',
            name='feature_table',
            field=models.JSONField(blank=True, default=list, verbose_name='特征表格数据'),
        ),
    ]
